const filters = {
    titles: [
        "Channel Sales Associate",
        "Outside Sales Associate",
        "Inside Sales Associate",
        "Senior Inside Sales Associate",
        "VP Outside Sales",
        "Vice President Inside Sales",
        "Benefits Specialist",
        "HR Specialist",
        "VP HR",
        "Videographer",
        "Junior Designer",
        "Copywriter",
        "Social Media Specialist",
        "Web Developer",
        "UX Developer",
        "Support Engineer",
        "Infrastructure Engineer",
        "Senior Software Engineer",
        "Senior Technical Engineer",
        "Senior Technical Support Engineer",
        "Director of Digital Marketing",
        "Technical Director",
        "Creative Director",
        "Director of Marketing",
        "Accounts Payable Administrator",
        "Accounts Receivable Administrator",
        "Payroll Administrator",
        "VP of Technology and Infrastructure",
        "VP of Engineering",
        "Chief Marketing Officer",
        "Chief Risk Officer",
        "Chief Operations Officer",
        "Chief Financial Officer",
        "Chief Technology Officer",
        "President"
    ],
    departments: [
        "Executive",
        "Engineering",
        "Information Technology",
        "Finance",
        "Operations",
        "Marketing",
        "Human Resources",
        "Sales"
    ],
    states: [
        "Alabama",
        "Alaska",
        "American Samoa",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "District of Columbia",
        "Federated States of Micronesia",
        "Florida",
        "Georgia",
        "Guam",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Marshall Islands",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Northern Mariana Islands",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Palau",
        "Pennsylvania",
        "Puerto Rico",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virgin Island",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming"
    ]
}

export default filters;